#include "SymbolPatterns.h"

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4244 4267)
#endif
#include <ida.hpp>
#include <bytes.hpp>
#include <name.hpp>
#include <entry.hpp>
#include <funcs.hpp>
#include <nalt.hpp>
#include <search.hpp>
#include <xref.hpp>
#include <fpro.h>
#include <kernwin.hpp>
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#include "Scanner.h"

#include <cstring>
#include <set>
#include <string>
#include <vector>

// Separator between fields in the pattern file.
// Signatures only contain hex digits, '?' and spaces, so '|' is unambiguous.
static const char g_FieldSeparator = '|';

// Entry kinds written as the first field of each line.
//   F = function: the signature points at the symbol itself.
//   G = global  : the signature points at a code reference to the symbol; on
//                 import the referenced data address is renamed.
//   R = function via reference: the function body itself couldn't be signed, so
//                 the signature points at a call/jump site; on import the
//                 referenced function address is renamed.
static const char g_KindFunction    = 'F';
static const char g_KindGlobal      = 'G';
static const char g_KindFunctionRef = 'R';

static std::string TrimTrailingSpaces(const std::string& p_Text)
{
	size_t s_End = p_Text.find_last_not_of(" \t\r\n");
	if (s_End == std::string::npos)
		return "";

	return p_Text.substr(0, s_End + 1);
}

// Instructions that reference a piece of data (used to sign globals).
static std::vector<ea_t> CollectDataReferences(ea_t p_Address)
{
	std::vector<ea_t> s_References;

	for (ea_t s_Ref = get_first_dref_to(p_Address); s_Ref != BADADDR; s_Ref = get_next_dref_to(p_Address, s_Ref))
	{
		if (is_code(get_flags(s_Ref)))
			s_References.push_back(s_Ref);
	}

	return s_References;
}

// Call/jump sites that reference a function (used to sign a function when its
// own body can't be signed uniquely).
static std::vector<ea_t> CollectFunctionReferences(ea_t p_Address)
{
	std::vector<ea_t> s_References;

	for (ea_t s_Ref = get_first_fcref_to(p_Address); s_Ref != BADADDR; s_Ref = get_next_fcref_to(p_Address, s_Ref))
	{
		if (is_code(get_flags(s_Ref)))
			s_References.push_back(s_Ref);
	}

	return s_References;
}

// Auto-generated names that IDA may still flag as regular names, so the flag
// checks alone won't filter them out (jump tables, RTTI, CFG thunks, etc.).
static bool HasAutoGeneratedPrefix(const char* p_Name)
{
	static const char* const s_Prefixes[] =
	{
		// dummy code/data names
		"sub_", "nullsub_", "j_", "loc_", "locret_", "def_", "jpt_",
		"off_", "seg_", "asc_", "byte_", "word_", "dword_", "qword_",
		"tbyte_", "xmmword_", "ymmword_", "zmmword_", "packreal_",
		"flt_", "dbl_", "stru_", "unk_", "algn_", "funcs_",
		"unknown_libname_",
		// MSVC mangled / compiler runtime
		"??_R", "??_7", "??_C", "__guard_", "_guard_", "__castguard_",
		nullptr,
	};

	for (const char* const* s_Prefix = s_Prefixes; *s_Prefix != nullptr; ++s_Prefix)
	{
		if (std::strncmp(p_Name, *s_Prefix, std::strlen(*s_Prefix)) == 0)
			return true;
	}

	return false;
}

// Addresses of all entry points (exports). Their names come from the binary.
static std::set<ea_t> CollectEntryPointAddresses()
{
	std::set<ea_t> s_Entries;

	const size_t s_Count = get_entry_qty();
	for (size_t i = 0; i < s_Count; ++i)
	{
		ea_t s_Address = get_entry(get_entry_ordinal(i));
		if (s_Address != BADADDR)
			s_Entries.insert(s_Address);
	}

	return s_Entries;
}

static int idaapi CollectImportCallback(ea_t p_Address, const char* /*p_Name*/, uval_t /*p_Ordinal*/, void* p_Param)
{
	if (p_Address != BADADDR)
		reinterpret_cast<std::set<ea_t>*>(p_Param)->insert(p_Address);

	return 1;
}

// Addresses of all imported symbols. Their names come from the import table.
static std::set<ea_t> CollectImportAddresses()
{
	std::set<ea_t> s_Imports;

	const uint s_Modules = get_import_module_qty();
	for (uint i = 0; i < s_Modules; ++i)
		enum_import_names((int) i, CollectImportCallback, &s_Imports);

	return s_Imports;
}

// True if the symbol at the address carries a meaningful user-assigned name,
// as opposed to an auto-generated name, an export, an import, or a FLIRT/thunk
// name. Both export (which symbols to write) and import (which symbols not to
// overwrite) share this heuristic.
static bool HasCustomName(ea_t p_Address, const std::set<ea_t>& p_EntryPoints, const std::set<ea_t>& p_Imports)
{
	if (!has_user_name(get_flags(p_Address)))
		return false;

	qstring s_Name;
	if (get_ea_name(&s_Name, p_Address) <= 0 || s_Name.empty())
		return false;

	if (!is_uname(s_Name.c_str()) || HasAutoGeneratedPrefix(s_Name.c_str()))
		return false;

	if (p_EntryPoints.count(p_Address) != 0 || p_Imports.count(p_Address) != 0)
		return false;

	// FLIRT library functions and thunks are not user renames.
	func_t* s_Func = get_func(p_Address);
	if (s_Func != nullptr && (s_Func->flags & (FUNC_LIB | FUNC_THUNK)) != 0)
		return false;

	return true;
}

void ExportRenamedSymbols()
{
	char* s_Path = ask_file(true, "*.sigme", "SigMe: export renamed symbol patterns");
	if (s_Path == nullptr)
		return;

	FILE* s_File = qfopen(s_Path, "w");
	if (s_File == nullptr)
	{
		msg("[SigMe] Could not open '%s' for writing.\n", s_Path);
		return;
	}

	qfputs("# SigMe symbol patterns: <kind>|<IDA signature>|<name>\n", s_File);

	const std::set<ea_t> s_EntryPoints = CollectEntryPointAddresses();
	const std::set<ea_t> s_Imports     = CollectImportAddresses();

	// Gather the symbols worth exporting up front so the progress bar tracks the
	// real work (signature generation) rather than the whole name list.
	struct Candidate { ea_t m_Address; std::string m_Name; };
	std::vector<Candidate> s_Candidates;

	const size_t s_NameCount = get_nlist_size();
	for (size_t i = 0; i < s_NameCount; ++i)
	{
		ea_t s_Address = get_nlist_ea(i);
		if (!HasCustomName(s_Address, s_EntryPoints, s_Imports))
			continue;

		const flags_t s_Flags = get_flags(s_Address);

		const char* s_Name = get_nlist_name(i);
		if (s_Name == nullptr || s_Name[0] == '\0')
			continue;

		// Ignore symbols starting with a (most likely auto-labelled ascii strings).
		if (!is_func(s_Flags) && s_Name[0] == 'a')
			continue;

		s_Candidates.push_back({ s_Address, s_Name });
	}

	size_t s_Exported = 0;
	size_t s_Skipped  = 0;

	const size_t s_Total = s_Candidates.size();
	msg("[SigMe] Exporting %d renamed symbol(s)...\n", (int) s_Total);

	bool s_Cancelled = false;
	show_wait_box("SigMe: exporting renamed symbols...");

	for (size_t i = 0; i < s_Total; ++i)
	{
		if (user_cancelled())
		{
			s_Cancelled = true;
			break;
		}

		const ea_t         s_Address = s_Candidates[i].m_Address;
		const std::string& s_Name    = s_Candidates[i].m_Name;

		const int s_Percent = (int) (i * 100 / s_Total);
		replace_wait_box("SigMe: exporting renamed symbols... %d%% (%d/%d)\n%s",
		                 s_Percent, (int) i, (int) s_Total, s_Name.c_str());

		// Build the list of places we can try to sign, in order of preference.
		// Functions sign themselves first, then fall back to call/jump sites that
		// reference them. Globals are data and can't be decoded, so we only have
		// the code references to them. Not every candidate yields a usable
		// signature, so we try each in turn until one works.
		struct Attempt { char m_Kind; ea_t m_Ea; };
		std::vector<Attempt> s_Attempts;

		if (is_func(get_flags(s_Address)))
		{
			s_Attempts.push_back({ g_KindFunction, s_Address });

			for (ea_t s_Ref : CollectFunctionReferences(s_Address))
				s_Attempts.push_back({ g_KindFunctionRef, s_Ref });
		}
		else
		{
			for (ea_t s_Ref : CollectDataReferences(s_Address))
				s_Attempts.push_back({ g_KindGlobal, s_Ref });

			if (s_Attempts.empty())
			{
				msg("[SigMe]   skip '%s': no code reference to global.\n", s_Name.c_str());
				++s_Skipped;
				continue;
			}
		}

		// Generate a unique signature so the symbol can be matched again.
		std::string s_Signature;
		char   s_Kind            = g_KindFunction;
		ea_t   s_SignatureEa     = BADADDR;
		size_t s_SignatureLength = 0;

		for (const Attempt& s_Attempt : s_Attempts)
		{
			Scanner s_Scanner(s_Attempt.m_Ea, true);
			s_Scanner.StartScanning();

			if (s_Scanner.HasError())
				continue;

			std::string s_Candidate = TrimTrailingSpaces(s_Scanner.GetSignature(Scanner::IDA));
			if (s_Candidate.empty())
				continue;

			s_Signature       = s_Candidate;
			s_Kind            = s_Attempt.m_Kind;
			s_SignatureEa     = s_Attempt.m_Ea;
			s_SignatureLength = s_Scanner.GetSignatureLength();
			break;
		}

		if (s_Signature.empty())
		{
			msg("[SigMe]   skip '%s': could not generate a signature.\n", s_Name.c_str());
			++s_Skipped;
			continue;
		}

		std::string s_Line = std::string(1, s_Kind) + g_FieldSeparator + s_Signature
		                   + g_FieldSeparator + s_Name + "\n";
		qfputs(s_Line.c_str(), s_File);
		++s_Exported;
		msg("[SigMe]   [%c] %s @ %a (%d bytes)\n",
		    s_Kind, s_Name.c_str(), s_SignatureEa, (int) s_SignatureLength);
	}

	hide_wait_box();
	qfclose(s_File);

	if (s_Cancelled)
		msg("[SigMe] Export cancelled by user after %d symbol(s).\n", (int) s_Exported);

	msg("[SigMe] Exported %d symbol pattern(s) to '%s' (%d skipped).\n",
	    (int) s_Exported, s_Path, (int) s_Skipped);
}

void ImportAndRenameSymbols()
{
	char* s_Path = ask_file(false, "*.sigme", "SigMe: import symbol patterns");
	if (s_Path == nullptr)
		return;

	FILE* s_File = qfopen(s_Path, "r");
	if (s_File == nullptr)
	{
		msg("[SigMe] Could not open '%s' for reading.\n", s_Path);
		return;
	}

	const ea_t s_MinEa = inf_get_min_ea();
	const ea_t s_MaxEa = inf_get_max_ea();

	const std::set<ea_t> s_EntryPoints = CollectEntryPointAddresses();
	const std::set<ea_t> s_Imports     = CollectImportAddresses();

	size_t s_Renamed   = 0;
	size_t s_NotFound  = 0;
	size_t s_Ambiguous = 0;
	size_t s_Existing  = 0;
	size_t s_Named     = 0;
	size_t s_Failed    = 0;

	msg("[SigMe] Importing symbol patterns from '%s'...\n", s_Path);

	// Read everything up front so the progress bar knows the total.
	std::vector<std::string> s_Lines;
	qstring s_LineBuf;
	while (qgetline(&s_LineBuf, s_File) >= 0)
		s_Lines.push_back(s_LineBuf.c_str());

	qfclose(s_File);

	const size_t s_Total = s_Lines.size();
	bool s_Cancelled = false;
	show_wait_box("SigMe: importing symbol patterns...");

	for (size_t i = 0; i < s_Total; ++i)
	{
		if (user_cancelled())
		{
			s_Cancelled = true;
			break;
		}

		const std::string& s_Line = s_Lines[i];

		// Skip comments and blank lines.
		if (s_Line.empty() || s_Line[0] == '#')
			continue;

		// Expected layout: <kind>|<signature>|<name>.
		size_t s_FirstSep = s_Line.find(g_FieldSeparator);
		if (s_FirstSep == std::string::npos)
			continue;

		size_t s_SecondSep = s_Line.find(g_FieldSeparator, s_FirstSep + 1);
		if (s_SecondSep == std::string::npos)
			continue;
		std::string s_KindField = TrimTrailingSpaces(s_Line.substr(0, s_FirstSep));
		std::string s_Signature = TrimTrailingSpaces(s_Line.substr(s_FirstSep + 1, s_SecondSep - s_FirstSep - 1));
		std::string s_Name       = TrimTrailingSpaces(s_Line.substr(s_SecondSep + 1));

		if (s_KindField.size() != 1 || s_Signature.empty() || s_Name.empty())
			continue;

		const char s_Kind = s_KindField[0];

		const int s_Percent = s_Total != 0 ? (int) (i * 100 / s_Total) : 100;
		replace_wait_box("SigMe: importing symbol patterns... %d%% (%d/%d)\n%s",
		                 s_Percent, (int) i, (int) s_Total, s_Name.c_str());

		// Skip entries whose name already exists somewhere in the database.
		if (get_name_ea(BADADDR, s_Name.c_str()) != BADADDR)
		{
			msg("[SigMe]   '%s' skipped: name already exists.\n", s_Name.c_str());
			++s_Existing;
			continue;
		}

		// Search the entire database for the pattern.
		ea_t s_Found = find_binary(s_MinEa, s_MaxEa, s_Signature.c_str(), 16, BIN_SEARCH_FORWARD);
		if (s_Found == BADADDR)
		{
			msg("[SigMe]   '%s' not found.\n", s_Name.c_str());
			++s_NotFound;
			continue;
		}

		// Reject patterns that match more than one location.
		ea_t s_Second = find_binary(s_Found + 1, s_MaxEa, s_Signature.c_str(), 16, BIN_SEARCH_FORWARD);
		if (s_Second != BADADDR)
		{
			msg("[SigMe]   '%s' skipped: signature matches multiple locations.\n", s_Name.c_str());
			++s_Ambiguous;
			continue;
		}

		// For functions the signature points at the symbol itself. For globals and
		// function references it points at a referencing instruction, so resolve
		// the address it refers to and rename that instead.
		ea_t s_Target = s_Found;
		if (s_Kind == g_KindGlobal)
		{
			s_Target = get_first_dref_from(s_Found);
			if (s_Target == BADADDR)
			{
				msg("[SigMe]   '%s' skipped: no data reference at %a.\n", s_Name.c_str(), s_Found);
				++s_Failed;
				continue;
			}
		}
		else if (s_Kind == g_KindFunctionRef)
		{
			s_Target = get_first_fcref_from(s_Found);
			if (s_Target == BADADDR)
			{
				msg("[SigMe]   '%s' skipped: no code reference at %a.\n", s_Name.c_str(), s_Found);
				++s_Failed;
				continue;
			}
		}

		// Don't clobber a symbol that already carries a user-assigned name.
		if (HasCustomName(s_Target, s_EntryPoints, s_Imports))
		{
			msg("[SigMe]   '%s' skipped: %a already has a custom name.\n", s_Name.c_str(), s_Target);
			++s_Named;
			continue;
		}

		if (set_name(s_Target, s_Name.c_str(), SN_NOCHECK | SN_FORCE))
		{
			msg("[SigMe]   renamed %a -> %s\n", s_Target, s_Name.c_str());
			++s_Renamed;
		}
		else
		{
			msg("[SigMe]   '%s' skipped: rename of %a failed.\n", s_Name.c_str(), s_Target);
			++s_Failed;
		}
	}

	hide_wait_box();

	if (s_Cancelled)
		msg("[SigMe] Import cancelled by user.\n");

	msg("[SigMe] Import complete: %d renamed, %d not found, %d ambiguous, %d name exists, %d already named, %d failed.\n",
	    (int) s_Renamed, (int) s_NotFound, (int) s_Ambiguous, (int) s_Existing, (int) s_Named, (int) s_Failed);
}
